# -*- coding: utf-8 -*-
# FONTES:
# https://github.com/wooorm/emoji-emotion/blob/master/Support.md
# https://gist.github.com/alopes/5358189
# https://github.com/wooorm/polarity
STOP_WORDS_PT_BR = ['de',
    'a',
    'o',
    'que',
    'e',
    'do',
    'da',
    'em',
    'um',
    'para',
    'é',
    'com',
    'não',
    'uma',
    'os',
    'no',
    'se',
    'na',
    'por',
    'mais',
    'as',
    'dos',
    'como',
    'mas',
    'foi',
    'ao',
    'ele',
    'das',
    'tem',
    'à',
    'seu',
    'sua',
    'ou',
    'ser',
    'quando',
    'muito',
    'há',
    'nos',
    'já',
    'está',
    'eu',
    'também',
    'só',
    'pelo',
    'pela',
    'até',
    'isso',
    'ela',
    'entre',
    'era',
    'depois',
    'sem',
    'mesmo',
    'aos',
    'ter',
    'seus',
    'quem',
    'nas',
    'me',
    'esse',
    'eles',
    'estão',
    'você',
    'tinha',
    'foram',
    'essa',
    'num',
    'nem',
    'suas',
    'meu',
    'às',
    'minha',
    'têm',
    'numa',
    'pelos',
    'elas',
    'havia',
    'seja',
    'qual',
    'será',
    'nós',
    'tenho',
    'lhe',
    'deles',
    'essas',
    'esses',
    'pelas',
    'este',
    'fosse',
    'dele',
    'tu',
    'te',
    'vocês',
    'vos',
    'lhes',
    'meus',
    'minha',
    'teu',
    'tu',
    'teu',
    'tua',
    'nosso',
    'noss',
    'nosso',
    'nossa',
    'dela',
    'delas',
    'esta',
    'estes',
    'estas',
    'aquele',
    'aquela',
    'aqueles',
    'aquelas',
    'isto',
    'aquilo',
    'esto',
    'est',
    'estamo',
    'estã',
    'estiv',
    'estev',
    'estivemo',
    'estivera',
    'estav',
    'estávamo',
    'estava',
    'estiver',
    'estivéramo',
    'estej',
    'estejamo',
    'esteja',
    'estivess',
    'estivéssemo',
    'estivesse',
    'estive',
    'estivermo',
    'estivere',
    'he',
    'h',
    'havemo',
    'hã',
    'houv',
    'houvemo',
    'houvera',
    'houver',
    'houvéramo',
    'haj',
    'hajamo',
    'haja',
    'houvess',
    'houvéssemo',
    'houvesse',
    'houve',
    'houvermo',
    'houvere',
    'houvere',
    'houver',
    'houveremo',
    'houverã',
    'houveri',
    'houveríamo',
    'houveria',
    'so',
    'somo',
    'sã',
    'er',
    'éramo',
    'era',
    'fu',
    'fo',
    'fomo',
    'fora',
    'for',
    'fôramo',
    'sej',
    'sejamo',
    'seja',
    'foss',
    'fôssemo',
    'fosse',
    'fo',
    'formo',
    'fore',
    'sere',
    'ser',
    'seremo',
    'serã',
    'seri',
    'seríamo',
    'seria',
    'tenh',
    'te',
    'temo',
    'té',
    'tinh',
    'tínhamo',
    'tinha',
    'tiv',
    'tev',
    'tivemo',
    'tivera',
    'tiver',
    'tivéramo',
    'tenh',
    'tenhamo',
    'tenha',
    'tivess',
    'tivéssemo',
    'tivesse',
    'tive',
    'tivermo',
    'tivere',
    'tere',
    'ter',
    'teremo',
    'terã',
    'teri',
    'teríamo',
    'teriam',
    '-',
    'é',
    'ver',
    'vem',
    '!',
    '?',
    '@'
]

# Lista de palavras e emojis e seus respectivos pontos
PONTOS_POLARIDADE = {
    'ud83d\udc7f':-5,
    'ud83d\ude3e': -5,
    'ud83d\ude21': -5,
    'ud83d\ude20': -4,
    'ud83d\ude27': -4,
    'ud83d\ude2d': -4,
    'ud83d\ude31': -4,
    'ud83d\ude40': -4,
    'ud83d\ude08': -4,
    'ud83d\ude1f': -4,
    'ud83d\ude3f': -2,
    'ud83d\ude15': -2,
    'ud83d\ude16': -2,
    'ud83d\ude30': -2,
    'ud83d\ude22': -2,
    'ud83d\ude1e': -2,
    'ud83d\ude33': -2,
    'ud83d\ude28': -2,
    'ud83d\ude2c': -2,
    'ud83d\ude2e': -2,
    'ud83d\ude23': -2,
    'ud83d\ude2b': -2,
    'ud83d\ude12': -2,
    'ud83d\ude29': -2,
    'ud83d\ude35': -1,
    'ud83d\ude25': -1,
    'ud83d\ude26': -1,
    'ud83d\ude01': -1,
    'ud83d\ude2f': -1,
    'ud83d\ude37': -1,
    'ud83d\ude14': -1,
    'ud83d\ude13': -1,
    'ud83d\ude1c': -1,
    'ud83d\ude11':0,
    'ud83d\ude36':0,
    'ud83d\ude10':0,
    'ud83d\ude34':0,
    'ud83d\ude1d':0,
    'ud83d\ude2a':0,
    'ud83d\ude06':1,
    'ud83d\ude0e':1,
    'ud83d\ude1b':1,
    'ud83d\ude32':3,
    'ud83d\ude0a':3,
    'ud83d\ude00':3,
    'ud83d\ude3d':3,
    'ud83d\ude19':3,
    'ud83d\ude17':3,
    'ud83d\ude1a':3,
    'u263a\ufe0f':3,
    'ud83d\ude0c':3,
    'ud83d\ude04':3,
    'ud83d\ude3c':3,
    'ud83d\ude38':3,
    'ud83d\ude03':3,
    'ud83d\ude3a':3,
    'ud83d\ude05':3,
    'ud83d\ude0f':3,
    'ud83d\ude3b':4,
    'ud83d\ude0d':4,
    'ud83d\ude07':4,
    'ud83d\ude02':4,
    'ud83d\ude39':4,
    'ud83d\ude18':4,
    'ud83d\ude09':4,
    'ud83d\ude0b':4,
    'ud83d\ude24':5,
    '#feliz': 5,
    'feliz': 5,
    'alegre': 5,
    'alegria': 5,
    'contente': 4,
    'satisfeito': 3,
    'bom': 3,
    'boa': 4,
    'happy': 4,
    '#happy': 4,
    'humor': 0,
    'triste': -4,
    '#triste': -4,
    'arrasado': -5,
    'decepcionado': -5,
    ':(': -5,
}
